/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Community.*;
import DBServer.PostIndex;
import DBServer.UserNameInfo;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicScrollPaneUI;
import GuiInitialize.ComponentsInit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JeongEun Bae <byg0922@naver.com>
 */
public class AddPostGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddPostGUI
     */
    int mousePX;
    int mousePY;
    String userID;
    String authority;
    String keyword;
    JTable Board;
    DefaultTableModel tableModel;
    
    public AddPostGUI() {
        initComponents();
        //jScrollPane1.setUI(new BasicScrollPaneUI());
        jScrollPane1.getViewport().setOpaque(false);

        System.out.println(jScrollPane1.getUI());
        System.out.println(ContentsField.getUI());
        OK.requestFocus();

        // setText("  " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))); 날짜 정보 (String)
    }

    public AddPostGUI(String userID, String authority, String keyword, JTable Board) {
        this.userID = userID;
        this.authority = authority;
        this.keyword = keyword;
        this.Board = Board;
        tableModel = (DefaultTableModel)Board.getModel();
        
        initComponents();
        //jScrollPane1.setUI(new BasicScrollPaneUI());
        jScrollPane1.getViewport().setOpaque(false);

        System.out.println(jScrollPane1.getUI());
        System.out.println(ContentsField.getUI());
        OK.requestFocus();

        WriterField.setText(userID);
        // setText("  " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))); 날짜 정보 (String)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovePanel = new javax.swing.JPanel();
        BackGroundPanel = new javax.swing.JPanel();
        FileNameField = new javax.swing.JTextField();
        Exit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContentsField = new javax.swing.JTextArea();
        AddFile = new javax.swing.JLabel();
        OK = new javax.swing.JLabel();
        TitleField = new javax.swing.JTextField();
        WriterField = new javax.swing.JTextField();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovePanel.setBackground(new java.awt.Color(255, 255, 255));
        MovePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovePanelMouseDragged(evt);
            }
        });
        MovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovePanelMousePressed(evt);
            }
        });
        MovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 560, 50));

        BackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(619, 773));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FileNameField.setBackground(new java.awt.Color(255, 255, 255,0));
        FileNameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FileNameField.setForeground(new java.awt.Color(204, 204, 204));
        FileNameField.setText("File Name");
        FileNameField.setBorder(null);
        FileNameField.setEnabled(false);
        FileNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FileNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FileNameFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(FileNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 340, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        BackGroundPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setUI(new BasicScrollPaneUI());
        jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane1MouseWheelMoved(evt);
            }
        });

        ContentsField.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        ContentsField.setColumns(20);
        ContentsField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ContentsField.setForeground(new java.awt.Color(204, 204, 204));
        ContentsField.setLineWrap(true);
        ContentsField.setRows(5);
        ContentsField.setText("Input Contents...");
        ContentsField.setBorder(null);
        ContentsField.setSelectionColor(new java.awt.Color(75, 184, 243));
        ContentsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContentsFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContentsFieldFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(ContentsField);

        BackGroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 470, 390));

        AddFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PostImage/AddFile.png"))); // NOI18N
        AddFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddFileMouseExited(evt);
            }
        });
        BackGroundPanel.add(AddFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 624, 120, 40));

        OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PostImage/OK.png"))); // NOI18N
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OKMouseExited(evt);
            }
        });
        BackGroundPanel.add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 690, 160, 50));

        TitleField.setBackground(new java.awt.Color(255, 255, 255,0));
        TitleField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TitleField.setForeground(new java.awt.Color(204, 204, 204));
        TitleField.setText("Input Title");
        TitleField.setBorder(null);
        TitleField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TitleFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TitleFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(TitleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 153, 480, 30));

        WriterField.setBackground(new java.awt.Color(255, 255, 255,0));
        WriterField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WriterField.setForeground(new java.awt.Color(204, 204, 204));
        WriterField.setText(" Writer");
        WriterField.setBorder(null);
        WriterField.setEnabled(false);
        WriterField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WriterFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                WriterFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(WriterField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 115, 105, 25));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PostImage/AddPost.png"))); // NOI18N
        BackGroundPanel.add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, 773));

        getContentPane().add(BackGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, 773));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WriterFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WriterFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(WriterField, " Writer");
    }//GEN-LAST:event_WriterFieldFocusGained

    private void WriterFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WriterFieldFocusLost
        // TODO add your handling code here:
        //IDField.setText(" ID");
        ComponentsInit.TextFieldLost(WriterField, " Wirter");
    }//GEN-LAST:event_WriterFieldFocusLost

    private void TitleFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TitleFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(TitleField, " Input Title");
    }//GEN-LAST:event_TitleFieldFocusGained

    private void TitleFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TitleFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(TitleField, " Input Title");
    }//GEN-LAST:event_TitleFieldFocusLost

    private void jScrollPane1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane1MouseWheelMoved
        // TODO add your handling code here:
        ComponentsInit.ScrollPaneMouseWheelMovedEvt(jScrollPane1, evt);
    }//GEN-LAST:event_jScrollPane1MouseWheelMoved

    private void ContentsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContentsFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextAreaGained(ContentsField, "Input Contents...");
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
    }//GEN-LAST:event_ContentsFieldFocusGained

    private void ContentsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContentsFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextAreaLost(ContentsField, "Input Contents...");
    }//GEN-LAST:event_ContentsFieldFocusLost

    private void AddFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFileMouseEntered
        // TODO add your handling code here:
        AddFile.setCursor(new Cursor(HAND_CURSOR));
        AddFile.setIcon(new ImageIcon(getClass().getResource("/PostImage/AddFile_Entered.png")));
    }//GEN-LAST:event_AddFileMouseEntered

    private void AddFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFileMouseExited
        // TODO add your handling code here:
        AddFile.setIcon(new ImageIcon(getClass().getResource("/PostImage/AddFile.png")));
    }//GEN-LAST:event_AddFileMouseExited

    private void OKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseEntered
        // TODO add your handling code here:
        OK.setCursor(new Cursor(HAND_CURSOR));
        OK.setIcon(new ImageIcon(getClass().getResource("/PostImage/OK_Entered.png")));
    }//GEN-LAST:event_OKMouseEntered

    private void OKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseExited
        // TODO add your handling code here:
        OK.setIcon(new ImageIcon(getClass().getResource("/PostImage/OK.png")));
    }//GEN-LAST:event_OKMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setCursor(new Cursor(HAND_CURSOR));
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px_1.png")));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png")));
    }//GEN-LAST:event_ExitMouseExited

    private void MovePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_MovePanelMousePressed

    private void MovePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousePX, y - mousePY);
    }//GEN-LAST:event_MovePanelMouseDragged

    private void FileNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FileNameFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(FileNameField, "File Name");
    }//GEN-LAST:event_FileNameFieldFocusGained

    private void FileNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FileNameFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(FileNameField, "File Name");
    }//GEN-LAST:event_FileNameFieldFocusLost

    private void OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseClicked
        // TODO add your handling code here:
        
        Post.Builder builder = new Post.Builder(TitleField.getText(), userID, ContentsField.getText(), authority);
        builder.postNumber(new PostIndex().getNextIndex());
        builder.keyWord(keyword);
         Vector<String> vec = new Vector<>();
        vec = new UserNameInfo(userID).informationSearch();
        builder.userName(vec.get(0));
        
        Post postinfo = builder.build();
        
        AddPost addpost = new AddPost(postinfo);
        addpost.add();
        
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        tableModel.insertRow(tableModel.getRowCount(), new Object[]{postinfo.getPostNumber(), postinfo.getTitle(), postinfo.getUserName(), date, postinfo.getViewCount(), postinfo.getCommentCount()});
        
        tableModel.fireTableDataChanged();
        
        this.dispose();
    }//GEN-LAST:event_OKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPostGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddFile;
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JTextArea ContentsField;
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField FileNameField;
    private javax.swing.JPanel MovePanel;
    private javax.swing.JLabel OK;
    private javax.swing.JTextField TitleField;
    private javax.swing.JTextField WriterField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
