/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ChatClient.*;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import GuiInitialize.ComponentsInit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicScrollPaneUI;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTML;

/**
 *
 * @author JeongEun Bae <byg0922@naver.com>
 */
public class Chatting extends javax.swing.JFrame {

    /**
     * Creates new form Chatting
     *
     * @throws javax.swing.text.BadLocationException
     * @throws java.io.IOException
     */
    int mousePX;
    int mousePY;
    ChatClient chatClient;
    CLIENT client;
    ChatSocketData chatsocketdata;
    
    public Chatting() throws BadLocationException, IOException {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        
        client = new CLIENT();
        
        TitleField.setText("Chatting Bang");
        ParticipantField.setText("배정은\n박채빈");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovePanel = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        BackGroundPanel = new javax.swing.JPanel();
        TitleField = new javax.swing.JTextField();
        ChatField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChatArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        ParticipantField = new javax.swing.JTextArea();
        FileSendBtn = new javax.swing.JLabel();
        SendBtn = new javax.swing.JLabel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovePanel.setBackground(new java.awt.Color(255, 255, 255));
        MovePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovePanelMouseDragged(evt);
            }
        });
        MovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovePanelMousePressed(evt);
            }
        });
        MovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 670, 40));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 40, 40));

        BackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleField.setBackground(new java.awt.Color(255, 255, 255,0));
        TitleField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TitleField.setForeground(new java.awt.Color(204, 204, 204));
        TitleField.setText("Title");
        TitleField.setBorder(null);
        TitleField.setEnabled(false);
        BackGroundPanel.add(TitleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 126, 450, 31));

        ChatField.setBackground(new java.awt.Color(255, 255, 255,0));
        ChatField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChatField.setForeground(new java.awt.Color(204, 204, 204));
        ChatField.setText("Input Contents");
        ChatField.setBorder(null);
        ChatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChatFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ChatFieldFocusLost(evt);
            }
        });
        ChatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatFieldActionPerformed(evt);
            }
        });
        BackGroundPanel.add(ChatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 470, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setOpaque(false);
        jScrollPane1.setUI(new BasicScrollPaneUI());
        jScrollPane2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane2MouseWheelMoved(evt);
            }
        });

        ChatArea.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        ChatArea.setColumns(20);
        ChatArea.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChatArea.setForeground(new java.awt.Color(204, 204, 204));
        ChatArea.setLineWrap(true);
        ChatArea.setRows(5);
        ChatArea.setBorder(null);
        ChatArea.setEnabled(false);
        ChatArea.setOpaque(false);
        ChatArea.setSelectionColor(new java.awt.Color(75, 184, 243));
        jScrollPane2.setViewportView(ChatArea);

        BackGroundPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 190, 520, 467));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setUI(new BasicScrollPaneUI());
        jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane1MouseWheelMoved(evt);
            }
        });

        ParticipantField.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        ParticipantField.setColumns(20);
        ParticipantField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ParticipantField.setForeground(new java.awt.Color(204, 204, 204));
        ParticipantField.setLineWrap(true);
        ParticipantField.setRows(5);
        ParticipantField.setText("Participant");
        ParticipantField.setBorder(null);
        ParticipantField.setEnabled(false);
        ParticipantField.setSelectionColor(new java.awt.Color(75, 184, 243));
        jScrollPane1.setViewportView(ParticipantField);

        BackGroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 195, 140, 450));

        FileSendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chatting/icons8_attach_25px_2.png"))); // NOI18N
        FileSendBtn.setToolTipText("");
        FileSendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FileSendBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FileSendBtnMouseExited(evt);
            }
        });
        BackGroundPanel.add(FileSendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 690, -1, 30));

        SendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chatting/Send.png"))); // NOI18N
        SendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SendBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SendBtnMouseExited(evt);
            }
        });
        BackGroundPanel.add(SendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, 100, 30));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chatting/ChatBackGround.png"))); // NOI18N
        BackGroundPanel.add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 729, 773));

        getContentPane().add(BackGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SendBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendBtnMouseEntered
        // TODO add your handling code here:
        SendBtn.setCursor(new Cursor(HAND_CURSOR));
        SendBtn.setIcon(new ImageIcon(getClass().getResource("/Chatting/Send_Entered.png")));
    }//GEN-LAST:event_SendBtnMouseEntered

    private void SendBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendBtnMouseExited
        // TODO add your handling code here:
        SendBtn.setIcon(new ImageIcon(getClass().getResource("/Chatting/Send.png")));
    }//GEN-LAST:event_SendBtnMouseExited

    private void jScrollPane1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane1MouseWheelMoved
        // TODO add your handling code here:
        ComponentsInit.ScrollPaneMouseWheelMovedEvt(jScrollPane1, evt);
    }//GEN-LAST:event_jScrollPane1MouseWheelMoved

    private void ChatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChatFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(ChatField, "Input Contents");
    }//GEN-LAST:event_ChatFieldFocusGained

    private void ChatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChatFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(ChatField, "Input Contents");
    }//GEN-LAST:event_ChatFieldFocusLost

    private void FileSendBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileSendBtnMouseEntered
        // TODO add your handling code here:
        FileSendBtn.setCursor(new Cursor(HAND_CURSOR));
        FileSendBtn.setIcon(new ImageIcon(getClass().getResource("/Chatting/icons8_attach_25px_3.png")));
    }//GEN-LAST:event_FileSendBtnMouseEntered

    private void FileSendBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileSendBtnMouseExited
        // TODO add your handling code here:
        FileSendBtn.setIcon(new ImageIcon(getClass().getResource("/Chatting/icons8_attach_25px_2.png")));
    }//GEN-LAST:event_FileSendBtnMouseExited

    private void SendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendBtnMouseClicked
        // TODO add your handling code here:
        String chatText = ChatField.getText();
        ChatSocketData chatsocketdata = new ChatSocketData("jeong", chatText);
        
        //chatClient.sendData(chatsocketdata);
        //ChatClient chatclient = new ChatClient(chatsocketdata, ChatArea);
        Chat chat = new Chat(chatsocketdata);
        ChatArea.setText(ChatArea.getText() + "\n" + chatsocketdata.SendData());
        
        
    }//GEN-LAST:event_SendBtnMouseClicked

    private void jScrollPane2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane2MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseWheelMoved

    private void MovePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousePX, y - mousePY);
    }//GEN-LAST:event_MovePanelMouseDragged

    private void MovePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_MovePanelMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setCursor(new Cursor(HAND_CURSOR));
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px_1.png")));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png")));
    }//GEN-LAST:event_ExitMouseExited

    private void ChatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ChatFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Chatting().setVisible(true);
            } catch (BadLocationException | IOException ex) {
                Logger.getLogger(Chatting.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JTextArea ChatArea;
    private javax.swing.JTextField ChatField;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FileSendBtn;
    private javax.swing.JPanel MovePanel;
    private javax.swing.JTextArea ParticipantField;
    private javax.swing.JLabel SendBtn;
    private javax.swing.JTextField TitleField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
