/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CSE_Client.ClientSocket;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import GuiInitialize.ComponentsInit;
import Login.FindInformation;
import javax.swing.JOptionPane;

/**
 *
 * @author JeongEun Bae <byg0922@naver.com>
 */
public class Find extends javax.swing.JFrame {

    /**
     * Creates new form Find
     */
    int mousePX;
    int mousePY;
    ComponentsInit componentsInit;
    boolean idSelected = true;
    //ClientSocket csr;

    public Find(/*ClientSocket csr*/) {
        initComponents();
        MovePanel.setBackground(new Color(255, 255, 255, 0));
        IDSelectPanel.setVisible(true);
        IDSelectPanel.setEnabled(true);

        PWSelectPanel.setVisible(false);
        PWSelectPanel.setEnabled(false);
        FindBtn1.requestFocus();

        //this.csr = csr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JLabel();
        PW = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        MovePanel = new javax.swing.JPanel();
        PWSelectPanel = new javax.swing.JPanel();
        IDField = new javax.swing.JTextField();
        PWQuestionField = new javax.swing.JComboBox<>();
        PWAnswerField = new javax.swing.JTextField();
        FindBtn1 = new javax.swing.JLabel();
        BackGroundLabel1 = new javax.swing.JLabel();
        IDSelectPanel = new javax.swing.JPanel();
        NameField = new javax.swing.JTextField();
        PhoneNumberField = new javax.swing.JTextField();
        FindBtn = new javax.swing.JLabel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 40));

        PW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/PW_NonSelect.png"))); // NOI18N
        PW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PWMouseEntered(evt);
            }
        });
        getContentPane().add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, 40));

        ID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/ID_Selected.png"))); // NOI18N
        ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IDMouseEntered(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 40, 40));

        MovePanel.setBackground(new java.awt.Color(255, 255, 255));
        MovePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovePanelMouseDragged(evt);
            }
        });
        MovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovePanelMousePressed(evt);
            }
        });
        MovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        PWSelectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDField.setBackground(new java.awt.Color(255, 255, 255,0));
        IDField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText(" ID");
        IDField.setBorder(null);
        IDField.setVerifyInputWhenFocusTarget(false);
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        PWSelectPanel.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 184, 260, 30));

        PWQuestionField.setBackground(new java.awt.Color(255, 255, 255,0));
        PWQuestionField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PWQuestionField.setForeground(new java.awt.Color(204, 204, 204));
        PWQuestionField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. 내가 나온 초등학교는?", "2. 나의 보물 1호는?", "3. 나의 첫사랑은?ㅋ", "4. 가장 기억에 남는 교수님은?", "5. 내가 태어난 지역은?" }));
        PWQuestionField.setToolTipText("");
        PWQuestionField.setBorder(null);
        PWQuestionField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PWQuestionField.setOpaque(false);
        PWQuestionField.setForeground(new Color(204,204,204));
        PWSelectPanel.add(PWQuestionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 277, 270, 30));

        PWAnswerField.setBackground(new java.awt.Color(255, 255, 255,0));
        PWAnswerField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PWAnswerField.setForeground(new java.awt.Color(204, 204, 204));
        PWAnswerField.setText(" ANSWER");
        PWAnswerField.setBorder(null);
        PWAnswerField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PWAnswerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PWAnswerFieldFocusLost(evt);
            }
        });
        PWAnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWAnswerFieldActionPerformed(evt);
            }
        });
        PWSelectPanel.add(PWAnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 325, 260, 30));

        FindBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/FIndBtn.png"))); // NOI18N
        FindBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FindBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FindBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FindBtn1MouseExited(evt);
            }
        });
        PWSelectPanel.add(FindBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 440, 170, 50));

        BackGroundLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/PWFindBG.png"))); // NOI18N
        PWSelectPanel.add(BackGroundLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

        getContentPane().add(PWSelectPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 550));

        IDSelectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameField.setBackground(new java.awt.Color(255, 255, 255,0));
        NameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameField.setForeground(new java.awt.Color(204, 204, 204));
        NameField.setText(" NAME");
        NameField.setBorder(null);
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        IDSelectPanel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 199, 260, 30));

        PhoneNumberField.setBackground(new java.awt.Color(255, 255, 255,0));
        PhoneNumberField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PhoneNumberField.setForeground(new java.awt.Color(204, 204, 204));
        PhoneNumberField.setText(" PHONE NUMBER");
        PhoneNumberField.setToolTipText("");
        PhoneNumberField.setBorder(null);
        PhoneNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneNumberFieldFocusLost(evt);
            }
        });
        PhoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberFieldActionPerformed(evt);
            }
        });
        IDSelectPanel.add(PhoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 295, 260, 30));

        FindBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/FIndBtn.png"))); // NOI18N
        FindBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FindBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FindBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FindBtnMouseExited(evt);
            }
        });
        IDSelectPanel.add(FindBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 440, 170, 50));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/FindBG.png"))); // NOI18N
        IDSelectPanel.add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

        getContentPane().add(IDSelectPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(NameField, "NAME");
    }//GEN-LAST:event_NameFieldFocusGained

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        // TODO add your handling code here:
        //IDField.setText(" ID");
        ComponentsInit.TextFieldLost(NameField, "NAME");
    }//GEN-LAST:event_NameFieldFocusLost

    private void PhoneNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(PhoneNumberField, " PHONE NUMBER");
    }//GEN-LAST:event_PhoneNumberFieldFocusGained

    private void PhoneNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(PhoneNumberField, " PHONE NUMBER");
    }//GEN-LAST:event_PhoneNumberFieldFocusLost

    private void FindBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindBtnMouseEntered
        // TODO add your handling code here:
        FindBtn.setCursor(new Cursor(HAND_CURSOR));
        FindBtn.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/FindBtn_Entered.png")));
    }//GEN-LAST:event_FindBtnMouseEntered

    private void FindBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindBtnMouseExited
        // TODO add your handling code here:
        FindBtn.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/FindBtn.png")));
    }//GEN-LAST:event_FindBtnMouseExited

    private void MovePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousePX, y - mousePY);
    }//GEN-LAST:event_MovePanelMouseDragged

    private void MovePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_MovePanelMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setCursor(new Cursor(HAND_CURSOR));
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px_1.png")));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png")));
    }//GEN-LAST:event_ExitMouseExited

    private void IDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMouseEntered
        // TODO add your handling code here:
        ID.setCursor(new Cursor(HAND_CURSOR));
        //ID.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/ID_Selected.png")));

    }//GEN-LAST:event_IDMouseEntered

    private void PWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PWMouseEntered
        // TODO add your handling code here:
        PW.setCursor(new Cursor(HAND_CURSOR));
        //PW.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/PW_Selected.png")));
    }//GEN-LAST:event_PWMouseEntered

    private void IDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMouseClicked
        // TODO add your handling code here:
        idSelected = true;
        ID.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/ID_Selected.png")));
        PW.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/PW_NonSelect.png")));

        IDSelectPanel.setVisible(true);
        IDSelectPanel.setEnabled(true);

        PWSelectPanel.setVisible(false);
        PWSelectPanel.setEnabled(false);
    }//GEN-LAST:event_IDMouseClicked

    private void PWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PWMouseClicked
        // TODO add your handling code here:
        idSelected = false;
        PW.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/PW_Selected.png")));
        ID.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/ID_NonSelect.png")));

        IDSelectPanel.setVisible(false);
        IDSelectPanel.setEnabled(false);

        PWSelectPanel.setVisible(true);
        PWSelectPanel.setEnabled(true);
    }//GEN-LAST:event_PWMouseClicked

    private void FindBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindBtn1MouseEntered
        // TODO add your handling code here:
        FindBtn1.setCursor(new Cursor(HAND_CURSOR));
        FindBtn1.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/FindBtn_Entered.png")));
    }//GEN-LAST:event_FindBtn1MouseEntered

    private void FindBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindBtn1MouseExited
        // TODO add your handling code here:
        FindBtn1.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/FindBtn.png")));
    }//GEN-LAST:event_FindBtn1MouseExited

    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(IDField, " ID");
    }//GEN-LAST:event_IDFieldFocusGained

    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        // TODO add your handling code here:
        //IDField.setText(" ID");
        ComponentsInit.TextFieldLost(IDField, " ID");
    }//GEN-LAST:event_IDFieldFocusLost

    private void PWAnswerFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PWAnswerFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(PWAnswerField, " ANSWER");
    }//GEN-LAST:event_PWAnswerFieldFocusGained

    private void PWAnswerFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PWAnswerFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(PWAnswerField, " ANSWER");
    }//GEN-LAST:event_PWAnswerFieldFocusLost

    private void FindBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindBtn1MouseClicked
        // TODO add your handling code here:
        String ID = IDField.getText();
        int selectQuestion = PWQuestionField.getSelectedIndex();
        String Answer = PWAnswerField.getText();

        FindInformation findInfoPW = new FindInformation(ID, selectQuestion, Answer);
        String result = findInfoPW.searchPWResult();

        if (!result.equals("")) {
            String str = "현재 회원님의 비밀번호는  " + result + " 입니다.";
            JOptionPane.showInternalMessageDialog(null, str);
        }
    }//GEN-LAST:event_FindBtn1MouseClicked

    private void FindBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindBtnMouseClicked
        // TODO add your handling code here:
        //  if (idSelected) {
//            System.out.println("ID선택");
        String name = NameField.getText();
        String phoneNumber = PhoneNumberField.getText();

        FindInformation findInfoID = new FindInformation(name, phoneNumber);
        String result = findInfoID.searchIDResult();
        System.out.println(result);
//             String result = findInfoID.searchIDResult(csr);
//             System.out.println("서버에게 값 전달");

        if (!result.equals("")) {
            String str = "현재 회원님의 아이디는  " + result + " 입니다.";
            JOptionPane.showInternalMessageDialog(null, str);
        }

        //}
    }//GEN-LAST:event_FindBtnMouseClicked

    private void PhoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberFieldActionPerformed
        // TODO add your handling code here:
        //if (idSelected) {
//            System.out.println("ID선택");
        String name = NameField.getText();
        String phoneNumber = PhoneNumberField.getText();

        FindInformation findInfoID = new FindInformation(name, phoneNumber);
        String result = findInfoID.searchIDResult();
        System.out.println(result);
//             String result = findInfoID.searchIDResult(csr);
//             System.out.println("서버에게 값 전달");

        if (!result.equals("")) {
            String str = "현재 회원님의 아이디는  " + result + " 입니다.";
            JOptionPane.showInternalMessageDialog(null, str);
            //}

        }
    }//GEN-LAST:event_PhoneNumberFieldActionPerformed

    private void PWAnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWAnswerFieldActionPerformed
        // TODO add your handling code here:
        String ID = IDField.getText();
        int selectQuestion = PWQuestionField.getSelectedIndex();
        System.out.println(selectQuestion);
        String Answer = PWAnswerField.getText();

        FindInformation findInfoPW = new FindInformation(ID, selectQuestion, Answer);
        String result = findInfoPW.searchPWResult();
        System.out.println(result);
        if (!result.equals("")) {
            String str = "현재 회원님의 비밀번호는  " + result + " 입니다.";
            JOptionPane.showInternalMessageDialog(null, str);
        }
    }//GEN-LAST:event_PWAnswerFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Find().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JLabel BackGroundLabel1;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FindBtn;
    private javax.swing.JLabel FindBtn1;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDField;
    private javax.swing.JPanel IDSelectPanel;
    private javax.swing.JPanel MovePanel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel PW;
    private javax.swing.JTextField PWAnswerField;
    private javax.swing.JComboBox<String> PWQuestionField;
    private javax.swing.JPanel PWSelectPanel;
    private javax.swing.JTextField PhoneNumberField;
    // End of variables declaration//GEN-END:variables
}
