package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import CSE_Client.ClientSocket;
import Login.Login;
import java.awt.Color;
import java.awt.Cursor;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JeongEun Bae <byg0922@naver.com>
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    int mousePX;
    int mousePY;
    //ClientSocket csr;

    public LoginPage() {
        initComponents();
        IDTextField1.setBackground(new Color(255, 255, 255, 0));
        PWTextField.setBackground(new Color(255, 255, 255, 0));
        //csr = ClientSocketRef.getInstance();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignUp = new javax.swing.JLabel();
        FindIDPW = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JLabel();
        IDTextField1 = new javax.swing.JTextField();
        PWTextField = new javax.swing.JPasswordField();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/회원가입.png"))); // NOI18N
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpMouseExited(evt);
            }
        });
        jPanel1.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 490, -1, 30));

        FindIDPW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/ID _ PW 찾기.png"))); // NOI18N
        FindIDPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FindIDPWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FindIDPWMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FindIDPWMouseExited(evt);
            }
        });
        jPanel1.add(FindIDPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 100, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/icons8_exit_40px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 40, 50));

        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 50));

        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/LOGIN_btn.png"))); // NOI18N
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 540, 130, 40));

        IDTextField1.setBackground(new java.awt.Color(255, 255, 255));
        IDTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        IDTextField1.setForeground(new java.awt.Color(153, 153, 153));
        IDTextField1.setBorder(null);
        IDTextField1.setOpaque(false);
        IDTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(IDTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 230, 40));

        PWTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PWTextField.setForeground(new java.awt.Color(153, 153, 153));
        PWTextField.setBorder(null);
        PWTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PWTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 230, 50));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/로그인배경2.png"))); // NOI18N
        BackGroundLabel.setToolTipText("");
        jPanel1.add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextField1ActionPerformed

    private void PWTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWTextFieldActionPerformed
        // TODO add your handling code herei
        String id = IDTextField1.getText();
        String pw = PWTextField.getText();
        
        if (id.matches("^[a-zA-Z0-9]{0,12}$") && pw.matches("^[a-zA-Z0-9!@#$*]{0,16}$")) { //id pw 형식 체크 (기준은 내 맘)
            // id pw가 DB에 있는지 확인 필요
            Login login = new Login(id, pw);
            //System.out.println("getInstance 호출 = " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss:SSS")));
            String userloginResult = login.loginResult();

            if (!userloginResult.equals("false")) {
                MainPage mp = new MainPage(id, userloginResult);
                mp.setVisible(true);
                mp.setEnabled(true);
                this.dispose();
            } // user 인지 admin 인지 체크해서 userType 넘겨줘야함
            else {
                JOptionPane.showInternalMessageDialog(null, "해당되는 ID와 PW의 회원이 존재하지 않습니다.");
            }
        } else {
            JOptionPane.showInternalMessageDialog(null, "ID, PW 형식 오류입니다.");
        }

    }//GEN-LAST:event_PWTextFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i += 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);

            try {
                Thread.sleep(25);
            } catch (InterruptedException e) {
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousePX, y - mousePY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setCursor(new Cursor(HAND_CURSOR));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/icons8_exit_40px_2.png")));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        // Exit.setCursor(new Cursor());
        //Exit.setIcon(new ImageIcon("/icons8_exit_40px.png"));
        Exit.setIcon(new ImageIcon(getClass().getResource("/LoginImage/icons8_exit_40px.png")));
    }//GEN-LAST:event_ExitMouseExited

    private void FindIDPWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindIDPWMouseEntered
        // TODO add your handling code here:
        FindIDPW.setCursor(new Cursor(HAND_CURSOR));
        FindIDPW.setIcon(new ImageIcon(getClass().getResource("/LoginImage/ID _ PW 찾기_MouseEntered.png")));
    }//GEN-LAST:event_FindIDPWMouseEntered

    private void SignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseEntered
        // TODO add your handling code here:
        SignUp.setCursor(new Cursor(HAND_CURSOR));
        SignUp.setIcon(new ImageIcon(getClass().getResource("/LoginImage/회원가입_MouseEntered.png")));
    }//GEN-LAST:event_SignUpMouseEntered

    private void FindIDPWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindIDPWMouseExited
        // TODO add your handling code here:
        FindIDPW.setIcon(new ImageIcon(getClass().getResource("/LoginImage/ID _ PW 찾기.png")));
    }//GEN-LAST:event_FindIDPWMouseExited

    private void SignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseExited
        // TODO add your handling code here:
        SignUp.setIcon(new ImageIcon(getClass().getResource("/LoginImage/회원가입.png")));
    }//GEN-LAST:event_SignUpMouseExited

    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        // TODO add your handling code here:
        LoginBtn.setCursor(new Cursor(HAND_CURSOR));
        LoginBtn.setIcon(new ImageIcon(getClass().getResource("/LoginImage/LOGIN_btn_Entered.png")));
    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        // TODO add your handling code here:
        LoginBtn.setIcon(new ImageIcon(getClass().getResource("/LoginImage/LOGIN_btn.png")));
    }//GEN-LAST:event_LoginBtnMouseExited

    private void FindIDPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindIDPWMouseClicked
        // TODO add your handling code here:
        Find find = new Find(/*csr*/);
        find.setVisible(true);
        find.setEnabled(true);
    }//GEN-LAST:event_FindIDPWMouseClicked

    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
        // TODO add your handling code here:
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
        signUp.setEnabled(true);
    }//GEN-LAST:event_SignUpMouseClicked

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked
        // TODO add your handling code here:
        String id = IDTextField1.getText();
        String pw = PWTextField.getText();

        if (id.matches("^[a-zA-Z0-9]{6,12}$") && pw.matches("^[a-zA-Z0-9!@#$*]{6,16}$")) { //id pw 형식 체크 (기준은 내 맘)
            Login login = new Login(id, pw);
            //System.out.println("getInstance 호출 = " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss:SSS")));
            //String result = login.loginResult(csr);
            String userloginResult = login.loginResult();

            if (!userloginResult.equals("false")) {
                MainPage mp = new MainPage(id, userloginResult);
                mp.setVisible(true);
                mp.setEnabled(true);
                this.dispose();
            } // user 인지 admin 인지 체크해서 userType 넘겨줘야함
            else {
                JOptionPane.showInternalMessageDialog(null, "해당되는 ID와 PW의 회원이 존재하지 않습니다.");
            }
        } else {
            JOptionPane.showInternalMessageDialog(null, "ID, PW 형식 오류입니다.");
        }

    }//GEN-LAST:event_LoginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FindIDPW;
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JLabel LoginBtn;
    private javax.swing.JPasswordField PWTextField;
    private javax.swing.JLabel SignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
