/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Cursor;
import javax.swing.ImageIcon;
import GuiInitialize.ComponentsInit;

/**
 *
 * @author JeongEun Bae <byg0922@naver.com>
 */
public class MyInfo extends javax.swing.JFrame {

    /**
     * Creates new form MyInfo
     */
    int mousePX;
    int mousePY;
    MainPage mp;
    public MyInfo() {
        initComponents();
    }

    public MyInfo(String userID, MainPage mp) {
        initComponents();
        this.mp = mp;
        // userID로 DB에서 정보를 찾고 TextField에 초기화 해줘야함
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovePanel = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        BackGroundPanel = new javax.swing.JPanel();
        GradeField = new javax.swing.JTextField();
        SchoolField = new javax.swing.JTextField();
        StudentNumberFIeld = new javax.swing.JTextField();
        MajorField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        Withdrawal = new javax.swing.JLabel();
        Modify = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovePanel.setBackground(new java.awt.Color(255, 255, 255));
        MovePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovePanelMouseDragged(evt);
            }
        });
        MovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovePanelMousePressed(evt);
            }
        });
        MovePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MovePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 700, 40));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 40, 40));

        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GradeField.setBackground(new java.awt.Color(255, 255, 255,0));
        GradeField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GradeField.setForeground(new java.awt.Color(204, 204, 204));
        GradeField.setText(" GRADE");
        GradeField.setToolTipText("");
        GradeField.setBorder(null);
        GradeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GradeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GradeFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(GradeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 138, 40, 30));

        SchoolField.setBackground(new java.awt.Color(255, 255, 255,0));
        SchoolField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SchoolField.setForeground(new java.awt.Color(204, 204, 204));
        SchoolField.setText("SCHOOL");
        SchoolField.setToolTipText("");
        SchoolField.setBorder(null);
        SchoolField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SchoolFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SchoolFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(SchoolField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 190, 30));

        StudentNumberFIeld.setBackground(new java.awt.Color(255, 255, 255,0));
        StudentNumberFIeld.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        StudentNumberFIeld.setForeground(new java.awt.Color(204, 204, 204));
        StudentNumberFIeld.setText(" STUDENT NUMBER");
        StudentNumberFIeld.setToolTipText("");
        StudentNumberFIeld.setBorder(null);
        StudentNumberFIeld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StudentNumberFIeldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                StudentNumberFIeldFocusLost(evt);
            }
        });
        BackGroundPanel.add(StudentNumberFIeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 239, 190, 30));

        MajorField.setBackground(new java.awt.Color(255, 255, 255,0));
        MajorField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MajorField.setForeground(new java.awt.Color(204, 204, 204));
        MajorField.setText(" MAJOR");
        MajorField.setToolTipText("");
        MajorField.setBorder(null);
        MajorField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MajorFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MajorFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(MajorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 339, 190, 30));

        NameField.setBackground(new java.awt.Color(255, 255, 255,0));
        NameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameField.setForeground(new java.awt.Color(204, 204, 204));
        NameField.setText("NAME");
        NameField.setBorder(null);
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 138, 80, 30));

        IDField.setBackground(new java.awt.Color(255, 255, 255,0));
        IDField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText(" ID");
        IDField.setBorder(null);
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        BackGroundPanel.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 188, 190, 30));

        Withdrawal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyInfo/Withdrawal.png"))); // NOI18N
        Withdrawal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WithdrawalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WithdrawalMouseExited(evt);
            }
        });
        BackGroundPanel.add(Withdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 100, -1));

        Modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyInfo/MyInfo_Modify.png"))); // NOI18N
        Modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModifyMouseExited(evt);
            }
        });
        BackGroundPanel.add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 100, -1));

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyInfo/LogOut.png"))); // NOI18N
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });
        BackGroundPanel.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 100, -1));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyInfo/MyInfo.png"))); // NOI18N
        BackGroundPanel.add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 759, 497));

        getContentPane().add(BackGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseEntered
        // TODO add your handling code here:
        LogOut.setCursor(new Cursor(HAND_CURSOR));
        LogOut.setIcon(new ImageIcon(getClass().getResource("/MyInfo/LogOut_Entered.png")));
    }//GEN-LAST:event_LogOutMouseEntered

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited
        // TODO add your handling code here:
        LogOut.setIcon(new ImageIcon(getClass().getResource("/MyInfo/LogOut.png")));
    }//GEN-LAST:event_LogOutMouseExited

    private void ModifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseEntered
        // TODO add your handling code here:
        Modify.setCursor(new Cursor(HAND_CURSOR));
        Modify.setIcon(new ImageIcon(getClass().getResource("/MyInfo/MyInfo_Modify_Entered.png")));
    }//GEN-LAST:event_ModifyMouseEntered

    private void ModifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseExited
        // TODO add your handling code here:
        Modify.setIcon(new ImageIcon(getClass().getResource("/MyInfo/MyInfo_Modify.png")));
    }//GEN-LAST:event_ModifyMouseExited

    private void WithdrawalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawalMouseEntered
        // TODO add your handling code here:
        Withdrawal.setCursor(new Cursor(HAND_CURSOR));
        Withdrawal.setIcon(new ImageIcon(getClass().getResource("/MyInfo/Withdrawal_Entered.png")));
    }//GEN-LAST:event_WithdrawalMouseEntered

    private void WithdrawalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawalMouseExited
        // TODO add your handling code here:
        Withdrawal.setIcon(new ImageIcon(getClass().getResource("/MyInfo/Withdrawal.png")));
    }//GEN-LAST:event_WithdrawalMouseExited

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        mp.dispose();
        this.dispose();
        
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_LogOutMouseClicked

    private void MovePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousePX, y - mousePY);
    }//GEN-LAST:event_MovePanelMouseDragged

    private void MovePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_MovePanelMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setCursor(new Cursor(HAND_CURSOR));
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px_1.png")));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setIcon(new ImageIcon(getClass().getResource("/SignUpImage/icons8_multiply_45px.png")));
    }//GEN-LAST:event_ExitMouseExited

    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(IDField, " ID");
    }//GEN-LAST:event_IDFieldFocusGained

    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        // TODO add your handling code here:
        //IDField.setText(" ID");
        ComponentsInit.TextFieldLost(IDField, " ID");
    }//GEN-LAST:event_IDFieldFocusLost

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(NameField, " NAME");
    }//GEN-LAST:event_NameFieldFocusLost

    private void MajorFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MajorFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(MajorField, " MAJOR");
    }//GEN-LAST:event_MajorFieldFocusGained

    private void MajorFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MajorFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(MajorField, " MAJOR");
    }//GEN-LAST:event_MajorFieldFocusLost

    private void StudentNumberFIeldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StudentNumberFIeldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(StudentNumberFIeld, " STUDENT NUMBER");
    }//GEN-LAST:event_StudentNumberFIeldFocusGained

    private void StudentNumberFIeldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StudentNumberFIeldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(StudentNumberFIeld, " STUDENT NUMBER");
    }//GEN-LAST:event_StudentNumberFIeldFocusLost

    private void GradeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GradeFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(GradeField, " GRADE");
    }//GEN-LAST:event_GradeFieldFocusGained

    private void GradeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GradeFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(GradeField, " GRADE");
    }//GEN-LAST:event_GradeFieldFocusLost

    private void SchoolFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SchoolFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(SchoolField, " GRADE");
    }//GEN-LAST:event_SchoolFieldFocusGained

    private void SchoolFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SchoolFieldFocusLost
        // TODO add your handling code here:
        ComponentsInit.TextFieldLost(SchoolField, " GRADE");
    }//GEN-LAST:event_SchoolFieldFocusLost

    private void NameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusGained
        // TODO add your handling code here:
        ComponentsInit.TextFieldGained(NameField, "NAME");
    }//GEN-LAST:event_NameFieldFocusGained

    private void ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ModifyMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MyInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField GradeField;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel LogOut;
    private javax.swing.JTextField MajorField;
    private javax.swing.JLabel Modify;
    private javax.swing.JPanel MovePanel;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField SchoolField;
    private javax.swing.JTextField StudentNumberFIeld;
    private javax.swing.JLabel Withdrawal;
    // End of variables declaration//GEN-END:variables
}
